server:
  port: 9003

spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://locahost:3306/spring-boot-demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.su.entity

#showSql
logging:
  level:
    com:
      su:
        mapper: debug
